default: &default
  adapter: postgresql
  port: 5432
  pool: 5
  timeout: 5000
  # host: localhost
  # username: postgres
  # password: postgres
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'postgres' %>

development:
  <<: *default
  database: devel_db

test:
  <<: *default
  database: test_db

production:
  <<: *default
  database: production_db
